name: release
on:
  push:
    branches:
      - main
      - fix-release
jobs:
  tag:
    name: Tag
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@2541b1294d2704b0964813337f33b291d3f8596b # v3.0.2
        with:
          fetch-depth: 0
      - name: Conventional Changelog Action
        uses: TriPSs/conventional-changelog-action@64b6a5db055a91612ec02cd77ea24a23e3437f12 # v3.11.0
        with:
          github-token: ${{ secrets.github_token }}
          skip-version-file: "true"
  goreleaser:
    name: Release
    needs: tag
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@2541b1294d2704b0964813337f33b291d3f8596b # v3.0.2
        with:
          fetch-depth: 0
      - name: Install Go
        uses: actions/setup-go@fcdc43634adb5f7ae75a9d7a9b9361790f7293e2 # v3.1.0
        with:
          go-version: 1.18
      - name: GoReleaser release
        uses: goreleaser/goreleaser-action@b953231f81b8dfd023c58e0854a721e35037f28b # v2.9.1
        with:
          distribution: goreleaser
          version: v1.9.1
          args: release --rm-dist
        env:
          GITHUB_TOKEN: ${{ secrets.github_token }}
